library(here)
library(data.table)
library(dplyr)

Coverage <- fread(here("data_in/Full_coverage.txt"), sep="\t", header=T)

old_names <- c(
  "SRR36459893","SRR36459892","SRR36459881","SRR36459877",
  "SRR36459876","SRR36459875","SRR36459874","SRR36459873",
  "SRR36459872","SRR36459871","SRR36459891","SRR36459890",
  "SRR36459889","SRR36459888","SRR36459887","SRR36459886",
  "SRR36459885","SRR36459884","SRR36459883","SRR36459882",
  "SRR36459880","SRR36459879","SRR36459878")

new_names <- c(
  "ANC","DMS1","DMS2","DMS3",
  "DMS4","CMB1","CMB2","CMB3",
  "CMB4","PTZ1","PTZ2","PTZ3",
  "PTZ4","TBF1","TBF2","TBF3",
  "TBF4","TBF1_05","TBF1_10","TBF1_15",
  "TBF1_20","TBF1_25","TBF1_30")

Coverage <- Coverage %>%
  rename(!!!setNames(old_names, new_names))

Coverage_order <- Coverage %>%
  select(1:2, all_of(new_names))


Coverage2 <- as.data.frame(Coverage_order)
Coverage2 <- split(Coverage2, Coverage2$Chr)

# how long is each chromosome?
lapply(Coverage2, function(x) length(t(x[,1])))

# Renamed bin function
calculate_bins <- function(ddn, line, len = 10000) {
  line.ddn <- lapply(ddn, "[", c(1, 2, line))
  bin_cov <- lapply(line.ddn, function(chrom_data) {
    chrom_data$bin <- cut(chrom_data$locus, breaks = seq(0, max(chrom_data$locus), by = len), labels = FALSE)
    tapply(chrom_data[[3]], chrom_data$bin, mean, na.rm = TRUE)
  })
  names(bin_cov) <- names(ddn)
  return(bin_cov)
}

# Note that "scaffolds" in the 233423 genome in Mycocosm are not numbered the same way as the 
# chromosomes in the PH1 reference genome in NCBI.
# Scaffold 1 = Chromosome 1
# Scaffold 2 = Chromosome 2
# Scaffold 3 = Chromosome 4
# Scaffold 4 = Chromosome 3
# Changed the ordering of the loop statement to plot in Chromosome order.
# Also have to manually set the alternating red and blue colours, below.
SWline <- function(bin){
  nm <-deparse(substitute(bin))
  # calculate the number of positions in the first chromosome
  x0 <- length(bin[[1]])
  #stand <- mean(unlist(bin[[1]]))
  stand <- mean(unlist(bin[[1]]))
  #stand <- mean(subset(Flu, coverage<500)$coverage)
  plot(1:    x0,  unlist(bin[[1]])/stand,  type="l", col="red", xlim=c(0, length(unlist(bin))), xaxt="n", yaxt="n", xlab="", ylab="", ylim=c(0, 3.5))
  for (i in c(2,4,3)){
    x1 <- length(bin[[i]])+x0-1
    x <- x0:x1
    stand <- median(unlist(bin[[1]]))
    #stand <- median(median(unlist(bin[[1]])),median(unlist(bin[[2]])),median(unlist(bin[[3]])),median(unlist(bin[[4]])),median(unlist(bin[[5]])),median(unlist(bin[[6]])),median(unlist(bin[[7]])),median(unlist(bin[[8]])),median(unlist(bin[[9]])),median(unlist(bin[[10]])),median(unlist(bin[[11]])),median(unlist(bin[[12]])),median(unlist(bin[[13]])))
    #stand <- mean(mean(unlist(bin[[1]])),mean(unlist(bin[[2]])),mean(unlist(bin[[3]])),mean(unlist(bin[[4]])),mean(unlist(bin[[5]])),mean(unlist(bin[[6]])),mean(unlist(bin[[7]])),mean(unlist(bin[[8]])),mean(unlist(bin[[9]])),mean(unlist(bin[[10]])),mean(unlist(bin[[11]])),mean(unlist(bin[[12]])),mean(unlist(bin[[13]])))
    points(c(x0:x1), unlist(bin[[i]]/stand), type="l", col=col[i])
    x0 <- x1
  }
  mtext(nm, side=3, adj=0.01, cex=0.7)  
  abline(h=1, lty=2)
  abline(h=2, lty=2)
  abline(h=3, lty=2)
  abline(h=4, lty=2)
  #axis(1,at=c(49,148,254,375,509,671,862,1067,1282,1511,1761,2037,2323),cex.axis=0.5,labels=FALSE)
}
col <- c("red", "blue", "blue", "red")

SWline_ANC <- function(bin){
  nm <-deparse(substitute(bin))
  # calculate the number of positions in the first chromosome
  x0 <- length(bin[[1]])
  #stand <- mean(unlist(bin[[1]]))
  stand <- mean(unlist(bin[[1]]))/mean(unlist(anc[[1]]))
  #stand <- mean(subset(Flu, coverage<500)$coverage)
  plot(1:    x0,  unlist(bin[[1]])/unlist(anc[[1]])/stand,  type="l", col="red", xlim=c(0, length(unlist(bin))), xaxt="n", yaxt="n", xlab="", ylab="", ylim=c(-0.25, 3.5))
  for (i in c(2,4,3)){
    print(i)
    x1 <- length(bin[[i]])+x0-1
    x <- x0:x1
    #stand <- median(unlist(bin[[1]]))
    #stand <- median(median(unlist(bin[[1]])),median(unlist(bin[[2]])),median(unlist(bin[[3]])),median(unlist(bin[[4]])),median(unlist(bin[[5]])),median(unlist(bin[[6]])),median(unlist(bin[[7]])),median(unlist(bin[[8]])),median(unlist(bin[[9]])),median(unlist(bin[[10]])),median(unlist(bin[[11]])),median(unlist(bin[[12]])),median(unlist(bin[[13]])))
    #stand <- mean(mean(unlist(bin[[1]])),mean(unlist(bin[[2]])),mean(unlist(bin[[3]])),mean(unlist(bin[[4]])),mean(unlist(bin[[5]])),mean(unlist(bin[[6]])),mean(unlist(bin[[7]])),mean(unlist(bin[[8]])),mean(unlist(bin[[9]])),mean(unlist(bin[[10]])),mean(unlist(bin[[11]])),mean(unlist(bin[[12]])),mean(unlist(bin[[13]])))
    points(c(x0:x1), unlist(bin[[i]])/unlist(anc[[i]])/stand, type="l", col=col[i])
    x0 <- x1
  }
  mtext(nm, side=3, adj=0.01, cex=0.7)  
  abline(h=0, lty=2)
  abline(h=1, lty=2)
  abline(h=2, lty=2)
  abline(h=3, lty=2)
  abline(h=4, lty=2)
  #axis(1,at=c(49,148,254,375,509,671,862,1067,1282,1511,1761,2037,2323),cex.axis=0.5,labels=FALSE)
}

# 5. Create normalized data for each sample
ANC <- calculate_bins(Coverage2, 3)
DMS1 <- calculate_bins(Coverage2, 4)
DMS2 <- calculate_bins(Coverage2, 5)
DMS3 <- calculate_bins(Coverage2, 6)
DMS4 <- calculate_bins(Coverage2, 7)
CMB1 <- calculate_bins(Coverage2, 8)
CMB2 <- calculate_bins(Coverage2, 9)
CMB3 <- calculate_bins(Coverage2, 10)
CMB4 <- calculate_bins(Coverage2, 11)
PTZ1 <- calculate_bins(Coverage2, 12)
PTZ2 <- calculate_bins(Coverage2, 13)
PTZ3 <- calculate_bins(Coverage2, 14)
PTZ4 <- calculate_bins(Coverage2, 15)
TBF1 <- calculate_bins(Coverage2, 16)
TBF2 <- calculate_bins(Coverage2, 17)
TBF3 <- calculate_bins(Coverage2, 18)
TBF4 <- calculate_bins(Coverage2, 19)
TBF1_05 <- calculate_bins(Coverage2, 20)
TBF1_10 <- calculate_bins(Coverage2, 21)
TBF1_15 <- calculate_bins(Coverage2, 22)
TBF1_20 <- calculate_bins(Coverage2, 23)
TBF1_25 <- calculate_bins(Coverage2, 24)
TBF1_30 <- calculate_bins(Coverage2, 25)

# 6. visualize the sample
anc <- ANC

png(file="figures_out/FigureS3A_DMS-PTZ_ANC.png", width=800, height=800, pointsize = 24)
par(mfrow=c(4, 2), mar=c(0.5, 1, 1.5, 2), oma=c(2, 3, 1, 1))
SWline_ANC(DMS1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(DMS2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(DMS3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(DMS4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(PTZ1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(PTZ2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(PTZ3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
SWline_ANC(PTZ4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
mtext("Depth of coverage", side=2, line = 1.5, outer=TRUE)
dev.off()


png(file="figures_out/FigureS3B_TBF-CMB_ANC.png", width=800, height=800, pointsize = 24)
par(mfrow=c(4, 2), mar=c(0.5, 1, 1.5, 2), oma=c(2, 3, 1, 1))
SWline_ANC(TBF1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(TBF2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(TBF3)
axis(2, las=2, at=c(1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(TBF4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(CMB1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(CMB2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline_ANC(CMB3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
SWline_ANC(CMB4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
dev.off()

for(i in c(1, 2, 4, 3)){
  print(i)
  stand <- mean(unlist(PTZ1[[1]]))/mean(unlist(ANC[[1]]))
  t <- PTZ2[[i]]/ANC[[i]]/stand
  print(subset(t, t <0.5 | t > 1.5))
}

png(file="figures_out/FigureS3A_DMS-PTZ.png", width=800, height=900, pointsize = 24)
par(mfrow=c(5, 2), mar=c(0.5, 1, 1.5, 2), oma=c(2, 3, 1, 1))
SWline(ANC)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(ANC)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(DMS1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(DMS2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(DMS3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(DMS4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(PTZ1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(PTZ2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(PTZ3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
SWline(PTZ4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
mtext("Depth of coverage", side=2, line = 1.5, outer=TRUE)
dev.off()


png(file="figures_out/FigureS3B_TBF-CMB.png", width=800, height=900, pointsize = 24)
par(mfrow=c(5, 2), mar=c(0.5, 1, 1.5, 2), oma=c(2, 3, 1, 1))
SWline(ANC)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(ANC)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(TBF1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(TBF2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(TBF3)
axis(2, las=2, at=c(1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(TBF4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(CMB1)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(CMB2)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "")
SWline(CMB3)
axis(2, las=2, at=c(0, 1, 2, 3))
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
SWline(CMB4)
axis(2, las=2, at=c(0, 1, 2, 3), labels=FALSE)
axis(1, at=length(ANC[[1]])/2, label = "Chr1")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])/2, label = "Chr2")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])/2, label = "Chr3")
axis(1, at=length(ANC[[1]])+length(ANC[[2]])+length(ANC[[3]])+length(ANC[[4]])/2, label = "Chr4")
dev.off()
